FROM bitnami/kafka:latest

# Switch to root user
USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-kafka python3-pandas vim-tiny libexpat1  && \ 
    python3 -m pip config set global.break-system-packages true && \ 
    pip3 install hdfs && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY ./hdfs /usr/lib/python3/dist-packages/hdfs
# Switch back to the default Kafka user to minimize security risk
USER 1001


